resource_types:
- name: rancher-deploy
  type: docker-image
  source:
    repository: chingor13/concourse_debug_resource

resources:
- name: resource-app-code
  type: git
  source:
    uri: https://github.com/chingor13/demoapp
    branch: master

- name: candidate-image
  type: docker-image
  source:
    repository: avvo/demoapp
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}
    tag: candidate

- name: final-image
  type: docker-image
  source:
    repository: avvo/demoapp
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}
    tag: latest

- name: stag
  type: rancher-deploy
  source:
    uri: https://rancher.stag.avvo.com:8080/
    username: {{rancher-username}}
    password: {{rancher-password}}
    data-center: stag

- name: production
  type: rancher-deploy
  source:
    uri: https://rancher.prod.avvo.com:8080/
    username: {{rancher-username}}
    password: {{rancher-password}}
    data-center: production

jobs:
- name: build-candidate
  plan:
  - get: resource-app-code
    trigger: true

  - put: candidate-image
    params:
      build: resource-app-code

- name: verify-build
  plan:
  - get: candidate-image
    trigger: true
    passed: [build-candidate]

  - task: unit-tests
    file: resource-app-code/ci/tasks/unit-tests.yml

- name: deploy-stag
  plan:
  - get: candidate-image
    trigger: true
    passed: [build-candidate]

  - put: stag
    params:
      foo: bar

- name: verify-stag
  plan:
  - get: candidate-image
    passed: [deploy-stag]

  - get: stag
    passed: [deploy-stag]
    trigger: true

  - task: acceptance-tests
    file: resource-app-code/ci/tasks/acceptance-tests.yml

- name: build-release
  plan:
  - get: candidate-image
    passed: [verify-stag, verify-build]
    trigger: true

  - put: final-image
    params:
      build: resource-app-code

- name: deploy-production
  plan:
  - get: final-image
    trigger: true
    passed: [build-release]

  - put: production
    params:
      foo: bar
