resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

- name: avvo-docker-image
  type: docker-image
  source:
    repository: avvo/docker-image-resource

resources:
- name: resource-app-code
  type: git
  source:
    uri: https://github.com/gaorlov/demoapp
    branch: master

- name: repo
  type: pull-request
  source:
    access_token: {{access-token}}
    repo: gaorlov/demoapp

- name: pr-image
  type: avvo-docker-image
  source:
    repository: avvo/demoapp
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}
    docker_host: {{docker-build-server}}

jobs:
- name: run tests for merge request
  plan:
  - get: repo
    trigger: true
  - put: repo
    params:
      path: repo
      status: pending
  - put: pr-image
    params:
      tag_prefix_command: cd repo ; cat .git/HEAD | grep -o "[a-z]*$" | xargs -i echo {}-
      build: repo
  - task: run tests
    config:
      platform: linux
      image_resource:
        type: avvo-docker-image
        source:
          repository: avvo/ruby
          username: {{dockerhub-username}}
          password: {{dockerhub-password}}
          dockerhost: {{docker-build-server}}
      inputs:
        - name: repo  
        - name: pr-image
          
      run:
        path: sh
        args:
        - -c
        - cd repo ;
        - gem install bundler ;
        - bundle install --local --without development ;
        - RAILS_ENV=test bin/rake test

  - put: repo
    params:
      path: repo
      status: success
